import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// Importing components

import FooterBar from "@/components/FooterBar";
import ScienceBackground from "@/components/ScienceBackground";
import NavBar from "@/components/NavBar";
import MatrixBackground from "@/components/MatrixBackground/MatrixBackground";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="App">

        <NavBar />
        {/* Animated background lives here */}
        <MatrixBackground />
        {children}
      <FooterBar />
      </body>
    </html>
  );
}
